/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Dev Inspector",
  "description": "Right-click a block to inspect it: identity, connections, inputs, stack outline, running threads, and editable block/project JSON.",
  "credits": [
    {
      "name": "Sophie"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "jsoneditor.css"
    },
    {
      "url": "style.css"
    }
  ],
  "tags": [
    "developer"
  ],
  "enabledByDefault": true
};
export default manifest;